### ISSUE TITLE
Error with rng

### ISSUE THREAD

**Issue by DavidRamosSal** [fbuessen/SpinMC.jl#3]
Hello, I was trying to run the two-dimensional honeycomb lattice example as found in the readme and got the following error:

> MethodError: no method matching var"#MonteCarlo#16"(::Int64, ::Int64, ::Int64, ::Int64, ::Random.Xoshiro, ::UInt64, ::Type{MonteCarlo}, ::Lattice{2, 3}, ::Float64, ::Int64, ::Int64)
> Closest candidates are:
>   var"#MonteCarlo#16"(::Int64, ::Int64, ::Int64, ::Int64, ::Random.MersenneTwister, ::UInt64, ::Type{MonteCarlo}, ::T, ::Float64, ::Int64, ::Int64) where T<:Lattice at ~/.julia/packages/SpinMC/iKQOo/src/MonteCarlo.jl:35

It worked giving the MonteCarlo function a specific seed.

**Comment by fbuessen** [comment]
This should be fixed now in #4. 
The problem was due to the MersenneTwister being hardcoded into the MonteCarlo struct. Upon creating a MonteCarlo instance, the code would attempt to create a local copy of Julia's global RNG -- which used to be MersenneTwister, but had been updated to Xoshiro recently.
